version: '3'

services:
  mongodb:
    image: mongo:4.1
    restart: always
    volumes:
      - simplechat_mongodb_data:/data/db
    ports:
      - 27017:27017

volumes:
  simplechat_mongodb_data:
    driver: local
